operador = input("Ingrese el operador (+, -, *, /): ")
O1= int(input("Ingrese el primer operador: "))
O2= int(input("Ingrese el segundo operador: "))
resultado = eval(str(O1) + operador + str(O2))
print ("El resultado de la operación es: ", resultado)